name: Tests

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    #- name: Run unit tests
    #  run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/*

    - name: API tests
      run: bash tests/api-tests.sh
